### PR TITLE
Support for Translator and Macros

### PR DESCRIPTION
**Pull request by MuhammadHammad001**
This pull request is linked to the feature enhancement PR#[80](https://github.com/riscv-software-src/riscv-isac/pull/80) created in RISC-V ISAC related to **Support for coverage of Privileged Architecture**

In this pull request, I have added:
1. The Translator feature support that has been created in collaboration with @allenjbaum.
2. The Macros feature that can be used to improve the coverpoint writing process. Hence, the user may use the riscof command for the coverage to use his/her macros in the test label like:
```c-objective
    RVTEST_CASE(1,"//check ISA:=regex(.*32.*); check ISA:=regex(.*I.*Zicsr.*); def rvtest_mtrap_routine=True; def rvtest_strap_routine=True; def TEST_CASE_1=True; mac self",PMP_TOR_priority_r)

```
And add the header_file for the macros in the CLI for riscof as:
```
riscof coverage --config=config.ini --cgf-file=dataset.cgf --cgf-file=testing_coverpoint.cgf --suite=Testing_dir --env=env -h /home/header_file.yaml
```

`Note: The documentation will be added within a day or two for the translator and the features as well for macros.`

@neelgala @pawks Please assign someone the reviewer for this PR as well.

@UmerShahidengr

### CODE REVIEW

**Comment by MuhammadHammad001** [comment]
@jamesbeyond

**Comment by jamesbeyond** [comment]
@MuhammadHammad001 

Thank for reminding, l'll take some time to review it,  meanwhile I requested other reviewer to have a look as well.

**Review by allenjbaum — APPROVED** [review]
LGTM

**Review by allenjbaum — APPROVED** [review]
LGTM

**Review by UmerShahidengr — APPROVED** [review]

**Pull request merged**
