### PR TITLE
fix a slight mistake

### PR DESCRIPTION
**Pull request by tiger9tu**
Signed-off-by: Tiger9Tu <76516415+Tiger9Tu@users.noreply.github.com>

### CODE REVIEW

**Review by jamesbeyond — DISMISSED** [review]
LGTM

**Comment by neelgala** [comment]
@Tiger9Tu  please rebase this PR to dev branch. Change target to dev branch. Also make an entry in CHANGELOG.md under the `WIP-DEV` branch.

**Comment by christian-herber-nxp** [comment]
is there anything happening on this one?

**Comment by jamesbeyond** [comment]
Hi @tiger9tu,

Sorry for the long delay, as we are working on a new process of contributions. 
`master` is currently the release branch, could you update your PR, and targeting it to the `dev` branch ?

**Review by jamesbeyond — APPROVED** [review]
LGTM

**Comment by Mudassir10X** [comment]
Shouldn't this PR be closed by now?

**Pull request merged**
