### PR TITLE
Added return code of 1 if any test failed

### PR DESCRIPTION
**Pull request by nadiga-ventana**

### CODE REVIEW

**Comment by pdonahue-ventana** [comment]
This is basically the same as https://gitlab.com/incoresemi/riscof/-/merge_requests/82 which was never reviewed.  @neelgala: What are your thoughts on returning non-zero on test failures so that higher-level scripts can detect that something is wrong?

**Comment by neelgala** [comment]
Apologies for not getting to this earlier.. 

This does make sense. I would suggest adding that logger statement as was done in the old PR. Also to accept this I will need you to do the following:
- rebase to master
- create entry in changelog for a patch version
-  bump the patch version using the command mentioned [here](https://github.com/riscv-software-src/riscof/blob/master/CONTRIBUTING.rst#deploying)

**Comment by nadiga-ventana** [comment]
@neelgala I have completed the mentioned steps. I also noticed that in the master the riscof/main.py has been deleted. I added it back in my pull request, but probably the recent changes has made my update moot.

**Comment by neelgala** [comment]
yea.. I was just going to say the same.. let me fix this in a separate PR.. keep this open until then.
@pawks fyi

**Comment by neelgala** [comment]
https://github.com/riscv-software-src/riscof/pull/21 should fix what was attempted in this PR

**Comment by neelgala** [comment]
closing this since the feature now exists on the main branch. Thanks for contribution :)

**Pull request closed without merging**
